// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
var SupplyChain = artifacts.require('SupplyChain');
const truffleAssert = require('truffle-assertions');

contract('SupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    var sku = 1
    var upc = 1
    const ownerID = accounts[0]
    const originFarmerID = accounts[1]
    const originFarmName = "John Doe"
    const originFarmInformation = "Yarray Valley"
    const originFarmLatitude = "-38.239770"
    const originFarmLongitude = "144.341490"
    var productID = sku + upc
    const productNotes = "Best beans for Espresso"
    const productPrice = web3.toWei(1, "ether")
    var itemState = 0
    const distributorID = accounts[2]
    const retailerID = accounts[3]
    const consumerID = accounts[4]
    const emptyAddress = '0x00000000000000000000000000000000000000'

    ///Available Accounts
    ///==================
    ///(0) 0x27d8d15cbc94527cadf5ec14b69519ae23288b95
    ///(1) 0x018c2dabef4904ecbd7118350a0c54dbeae3549a
    ///(2) 0xce5144391b4ab80668965f2cc4f2cc102380ef0a
    ///(3) 0x460c31107dd048e34971e57da2f99f659add4f02
    ///(4) 0xd37b7b8c62be2fdde8daa9816483aebdbd356088
    ///(5) 0x27f184bdc0e7a931b507ddd689d76dba10514bcb
    ///(6) 0xfe0df793060c49edca5ac9c104dd8e3375349978
    ///(7) 0xbd58a85c96cc6727859d853086fe8560bc137632
    ///(8) 0xe07b5ee5f738b2f87f88b99aac9c64ff1e0c7917
    ///(9) 0xbd3ff2e3aded055244d66544c9c059fa0851da44

    console.log("ganache-cli accounts used here...")
    console.log("Contract Owner: accounts[0] ", accounts[0])
    console.log("Farmer: accounts[1] ", accounts[1])
    console.log("Distributor: accounts[2] ", accounts[2])
    console.log("Retailer: accounts[3] ", accounts[3])
    console.log("Consumer: accounts[4] ", accounts[4])

    it("Test for adding producers", async() => {
        const supplyChain = await SupplyChain.deployed()

        let addproducertx = await supplyChain.addProducer(originFarmerID)
        const isProducerTrue = await supplyChain.isProducer(originFarmerID)
        const isProducerFalse = await supplyChain.isProducer(retailerID)
        
        truffleAssert.eventEmitted(addproducertx, 'ProducerAdded');
        assert.equal(isProducerTrue, true)
        assert.equal(isProducerFalse, false)
    })

    it("Test for adding distributors", async() => {
        const supplyChain = await SupplyChain.deployed()

        let adddistributortx = await supplyChain.addDistributor(distributorID)
        const isDistributorTrue = await supplyChain.isDistributor(distributorID)
        const isDistributorFalse = await supplyChain.isDistributor(originFarmerID)
        
        truffleAssert.eventEmitted(adddistributortx, 'DistributorAdded');
        assert.equal(isDistributorTrue, true)
        assert.equal(isDistributorFalse, false)
    })

    it("Test for adding retailers", async() => {
        const supplyChain = await SupplyChain.deployed()

        let addretailertx = await supplyChain.addRetailer(retailerID)
        const isRetailerTrue = await supplyChain.isRetailer(retailerID)
        const isRetailerFalse = await supplyChain.isRetailer(originFarmerID)
        
        truffleAssert.eventEmitted(addretailertx, 'RetailerAdded');
        assert.equal(isRetailerTrue, true)
        assert.equal(isRetailerFalse, false)
    })

    // 1st Test
    it("Testing smart contract function produceDrug() that allows a farmer to harvest coffee", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Mark an item as Harvested by calling function produceDrug()
        let producedtx = await supplyChain.produceDrug(upc, originFarmName, originFarmInformation, originFarmLatitude, originFarmLongitude, 
            productNotes, retailerID, distributorID, {from: originFarmerID})
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBufferOne[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferOne[2], originFarmerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferOne[3], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBufferOne[4], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBufferOne[5], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBufferOne[6], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBufferOne[7], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
        assert.equal(resultBufferTwo[5], 0, 'Error: Invalid item State')
        assert.equal(resultBufferTwo[6], retailerID, 'Error: Invalid retailer')
        assert.equal(resultBufferTwo[7], distributorID, 'Error: Invalid distributor')
        assert.equal(resultBufferTwo[8], 0, 'Error: Invalid consumer')
        truffleAssert.eventEmitted(producedtx, 'Produced');
    })

    // 2nd Test
    it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async() => {

        const supplyChain = await SupplyChain.deployed()

        // Mark an item as Harvested by calling function produceDrug()
        let tx2 = await supplyChain.shipItem(upc)

        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)
        
        truffleAssert.eventEmitted(tx2, 'Shipped');
        assert.equal(resultBufferTwo[5], 1, 'Error: Invalid item State')
              
    })

    // 2nd Test
    it("Testing smart contract function receiveItem() that allows a retailer to recive a drug", async() => {

        const supplyChain = await SupplyChain.deployed()
        // Mark an item as Harvested by calling function produceDrug()
        let txreceived = await supplyChain.receiveItem(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)
        truffleAssert.eventEmitted(txreceived, 'Received');
        assert.equal(resultBufferTwo[5], 2, 'Error: Invalid item State')
              
    })

    // 2nd Test
    it("Testing smart contract function receiveItem() that allows a retailer to recive a drug", async() => {

        const supplyChain = await SupplyChain.deployed()
        // Mark an item as Harvested by calling function produceDrug()
        let txowned = await supplyChain.buyItem(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)
        truffleAssert.eventEmitted(txowned, 'Owned');
        assert.equal(resultBufferTwo[5], 3, 'Error: Invalid item State')
              
    })



      
  

});

